name: Update Values on Release

# Trigger the create release workflow
on:
  push:
    tags:
      - 'v*' # Trigger only in case of new tag

jobs:
  update_values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --global user.email "amanjn82@gmail.com"
            git config --global user.name "Aman Chhabra"
            release_tag=${{ github.event.release.tag_name }}
            # Update the value in the specified file (replace with your details)
            npx yaml-update -f hackkerRankSolutions/version.go version=$release_tag
            git add hackkerRankSolutions/version.go
            git commit -m "Update version to $release_tag in actions.yaml"
            git push origin main
