name: Update Values on Tag

on:
  push:
    tags:
      - 'v*' # Trigger only in case of new tag

jobs:
  update_values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --global user.email "amanjn82@gmail.com"
            git config --global user.name "Aman Chhabra"
            echo "Release Tag: ${{ github.ref_name }}"
            release_tag="${{ github.ref_name }}"
            # Update the value in the specified file (replace with your details)
            sed -i "s/const version = .*/const version = \"$release_tag\"/" ../../version.go
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update version"
          git push
            
        
