name: Update Values on Tag

on:
  push:
    tags:
      - 'v*' # Trigger only in case of new tag

jobs:
  update_values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo "Release Tag: ${{ github.ref_name }}"
            release_tag="${{ github.ref_name }}"
      - name: Run update script
        with:
        python-version: '3.9.6'
        script: |
            python update_constant.py \
            --file_path ../../version.go \
            --constant_name version \
            --new_value $release_tag
      - name: Commit and push changes
        run: |
          git config --local user.email "amanjn82@gmail.com"
          git config --local user.name "amanjn98"
          git add .
          git commit -m "Update version"
          git push
            
        
